$color = rgba(00, 00, 00, 1.0)
$inner_color = rgba(47, 27, 27, 0.8)
# $outer_color = rgba(217, 175, 167, 1.0)
$font_color = rgba(217, 175, 167, 1.0)
$check_color = rgba(255, 107, 74, 1.0)

general {
    ignore_empty_input = true
    hide_cursor = true
    disable_loading_bar = true
    grace = 0
}

background {
    monitor =
    color = $color
    path = 
    blur_passes = 0
    blur_size = 0
    noise = 0.0117
    contrast = 1.3000
    brightness = 0.8000
    vibrancy = 0.2100
    vibrancy_darkness = 0.0
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fade, 1, 1.5, linear
}

label {
    monitor =
    text = cmd[update:1000] echo "<span>$(date +"%H:%M")</span>"
    color = $font_color
    font_size = 130
    font_family = JetBrainsMono Nerd Font ExtraLight
    position = 0, 200
    halign = center
    valign = center
    shadow_passes = 2
    shadow_size = 4
    shadow_color = rgb(0,0,0)
}

label {
    monitor =
    text = cmd[update:1000] echo "<span>$(date +"%A, %d %B")</span>"
    color = $font_color
    font_size = 18
    font_family = JetBrainsMono Nerd Font Bold
    position = 0, 80
    halign = center
    valign = center
    shadow_passes = 1
    shadow_size = 2
}

shape {
    monitor =
    size = 360, 2
    color = $font_color
    rounding = 0
    position = 0, 30
    halign = center
    valign = center
    shadow_passes = 1
}

label {
    monitor =
    text = "איך האָב דיר אַזוי פֿיל צו זאָגן, אַז איך האָב מורא איך וועל דיר גאָרנישט זאָגן"
    color = $font_color
    font_size = 12
    font_family = JetBrainsMono Nerd Font Italic
    position = 0, -20
    halign = center
    valign = center
    shadow_passes = 1
}

label {
    monitor =
    text = <span text_transform="lowercase">  $USER</span>
    color = $font_color
    font_size = 11
    font_family = monospace
    position = 0, -90
    halign = center
    valign = center
    shadow_passes = 1
}

input-field {
    monitor =
    size = 300, 45
    position = 0, -160
    halign = center
    valign = center
    inner_color = rgba(0, 0, 0, 0.0)
    outer_color = $outer_color
    outline_thickness = 2
    font_family = JetBrainsMono Nerd Font
    font_color = $font_color
    placeholder_text = <span foreground="gray">󰌾 Authenticate</span>
    check_color = $check_color
    fail_text = <i>$FAIL ($ATTEMPTS)</i>
    fail_color = rgb(cc3333)
    rounding = 0
    shadow_passes = 2
    shadow_size = 4
    fade_on_empty = false
}

auth {
    fingerprint:enabled = false
}
