# Environment
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# Core services
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = waybar
exec-once = mako
exec-once = hypridle
exec-once = swayosd-server

# Utilities
exec-once = gslapper --fork eDP-1 /home/nomnomheapnom/.config/hypr/mars-1.png
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = walker --gapplication-service
exec-once = elephant

