# Control your input devices
# See https://wiki.hyprland.org/Configuring/Variables/#input
input {
  # Change speed of keyboard repeat
  repeat_rate = 50
  repeat_delay = 300

  # Start with numlock on by defaulti
  numlock_by_default = true

  # Increase sensitivity for mouse/trackpad (default: 0)
  sensitivity = 0.5
  accel_profile = flat

  # Turn off mouse acceleration (default: false)
  force_no_accel = true

  touchpad {
    # Use natural (inverse) scrolling
    natural_scroll = true

    # Control the speed of your scrolling
    scroll_factor = 1.0

    # Enable the touchpad while typing
    # disable_while_typing = false
  }
}

gestures {
  #workspace_swipe = true
  #workspace_swipe_fingers = 3
}
